repos:
  - repo: local
    hooks:
      - id: nph
        name: nph (Nim formatter)
        entry: nph
        language: system
        types: [file]
        files: \.nim$
        pass_filenames: true
