# begin Nimble config (version 2)
when withDir(thisDir(), system.fileExists("nimble.paths")):
  include "nimble.paths"
# end Nimble config

# CI sibling-source path-override. CI doesn't run `nimble setup`
# (would burn time on dep resolution); instead it clones nim-debra
# and nim-typestates as siblings (see `.github/workflows/build.yml`
# "Clone and install sibling deps" step) and relies on these path
# overrides. Local dev users with `nimble.paths` (regenerated by
# `nimble setup` whenever deps shift) get the published versions; CI
# without `nimble.paths` falls back to the sibling clones.
const TypestatesSrc = thisDir() & "/../nim-typestates/src"
const DebraRoot = thisDir() & "/../nim-debra"
when dirExists(TypestatesSrc):
  switch("path", TypestatesSrc)
when dirExists(DebraRoot):
  switch("path", DebraRoot)
