# begin Nimble config (version 2)
when withDir(thisDir(), system.fileExists("nimble.paths")):
  include "nimble.paths"
# end Nimble config

# CI sibling-source path-override.
#
# CI doesn't run `nimble setup` (would burn time on dep resolution);
# instead it clones nim-debra + nim-typestates as siblings (see
# `.github/workflows/build.yml` "Clone and install sibling deps" step)
# and relies on the path overrides below. Local dev users with
# `nimble.paths` (regenerated by `nimble setup` whenever deps shift)
# get the published versions; CI without `nimble.paths` falls back to
# the sibling clones.
#
# The `when` guards on `dirExists` mean local-only checkouts that
# never cloned siblings keep their `nimble.paths` resolution and skip
# these overrides cleanly.
when withDir(thisDir(), system.dirExists("../nim-typestates/src")):
  switch("path", thisDir() & "/../nim-typestates/src")
when withDir(thisDir(), system.dirExists("../nim-debra")):
  switch("path", thisDir() & "/../nim-debra")
